### ISSUE TITLE
how to install this script?

### ISSUE THREAD

**Issue by dilshad217** [wodim/fearqdb#12]
hello i'm new to these things so sorry if it is dumb question,
i've downloaded the project and placed the file on my hosting, uploaded the sql file and edited config file also, now it just shows the home page with "Page not found
Are you lost? Go back",
how can i setup admin account and install this properly?

**Comment by wodim** [comment]
Follow these steps, starting from point 8: https://thacid.wordpress.com/2012/04/25/installing-fearqdb-on-debian-lighttpd-in-10-steps/

I know how complicated it is, but this project is practically abandoned right now.
